### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by oliveiramsk** [KalilBalech/AdvogadoAquiWebscraping#1]
Hey bro, sou novo no mundo dev, e seu projeto AdvogadoAquiWebscraping me chamou atenção.

Pode me dar uma direção pra onde seguir para que eu possa compreender seu código?

Ficaria extremamente feliz =)

Obrigado!

**Comment by KalilBalech** [comment]
Fala aí, mano

**Comment by KalilBalech** [comment]
Tem whatsapp?

**Comment by oliveiramsk** [comment]
Opa, tenho sim!

https://gist.githubusercontent.com/oliveiramsk/d50a7c4c7bc2716d340f81fb57e50495/raw/6136124045da8a86d526357f15eba9137e016299/tt.txt

**Comment by KalilBalech** [comment]
o link que você mandou não está funcionando. Manda o seu whatsapp aí

**Comment by oliveiramsk** [comment]
45-99125-6409
